FROM scratch
COPY main/conf_{{ .env }}.json /home/{{ .projectName }}.json
COPY {{ .execBuildTarget }} /home/{{ .projectName }}
ENTRYPOINT ["/home/{{ .projectName }}", "-conf", "/home/{{ .projectName }}.json"]