name: Build docker image
on: [push]

jobs:
  build:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.BUILD_TOKEN }}
          USER: ${{ github.actor }}
        run: git config --global url."https://${USER}:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: build go project
        run: go build -o main/main main/main.go
        env:
          GO111MODULE: on
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64

      - name: Push to GitHub Packages # doc: https://github.com/marketplace/actions/docker-build-push
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          dockerfile: Dockerfile_prod
          tag: ${{ github.sha }}
          image: k8sdemo/prod
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.BUILD_TOKEN }}
      - name: get the image url
        run: echo "::set-env name=ImageUrl::docker.pkg.github.com/ftwooo/k8sdemo/prod:${{ github.sha }}"
      - name: update k8s file
        run:  sed -i -e "s?image:.*?image:\ $ImageUrl?" k8s_prod.yml
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
            author_name: ${{ github.actor }}
            author_email: actions@github.com
            message: "Update k8s file"
            add: "k8s_prod.yml"
        env:
            GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}