name: Greet Everyone
on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'
      - name: build go project
        run: go build -o main/main main/main.go
        env:
          GO111MODULE: on
          GOPRIVATE: github.com/rexue2019/*
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64