name: Build docker image
on: [push]

jobs:
  build:
    name: build go binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'
      - run: |
          git config --local --remove-section http."https://github.com/"
          git config --global url."https://${GH_TOKEN}:x-oauth-basic@github.com/rexue2019/".insteadOf "https://github.com/rexue2019/"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build go project
        run: go build -o main/main main/main.go
        env:
          GO111MODULE: on
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64
