name: Build docker image
on: [push]

jobs:
  build:
    name: build go binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.BUILD_TOKEN }}
        run: git config --global url."https://ftwooo:${TOKEN}@github.com".insteadOf "https://github.com"
      - name: build go project
        run: go build -o main/main main/main.go
        env:
          GO111MODULE: on
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
            username: ${{ github.actor }}
            password: ${{ secrets.BUILD_TOKEN }}
            registry: docker.pkg.github.com
            repository: rexue2019/k8sdemo/prod
            tag_with_ref: true
