name: Greet Everyone
on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'
      - run: |
          git config --local --remove-section http."https://github.com/"
          git config --global url."https://github.com/".insteadOf "https://${GH_TOKEN}:x-oauth-basic@github.com/"
          git config --global url."git@github.com:".insteadOf "https://${GH_TOKEN}:x-oauth-basic@github.com/"

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build go project
        run: go build -o main/main main/main.go
        env:
          GO111MODULE: on
          GOPRIVATE: github.com/rexue2019/*
          CGO_ENABLED: 0
          GOOS: linux
          GOARCH: amd64
